sudo: required

language: node_js

node_js:
  - "6.9.1"

services:
  - docker

script:
  - npm run build

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t anttti/wordpress .
  - docker push anttti/wordpress
