sudo: required

language: node_js

node_js:
  - "6.9.1"

services:
  - docker

script:
  - npm run build

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD;
    docker build -t anttti/wordpress . ;
    docker push anttti/wordpress;
    fi