sudo: required

language: node_js

node_js:
  - "6.9.1"

services:
  - docker

script:
  - npm run build

after_success:
  - echo $DOCKER_USERNAME
  - echo $DOCKER_PASSWORD
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker build -t anttti/wordpress . ;
    docker push anttti/wordpress;
    fi